apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbus-jobsched
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbus-jobsched
  template:
    metadata:
      labels:
        app: sbus-jobsched
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sbus-jobsched
        image:  <<registryname>>.azurecr.io/<<my-repository-name>>:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: sbus-jobsched
---
apiVersion: v1
kind: Service
metadata:
  name: sbus-jobsched
spec:
  ports:
  - port: 6379
  selector:
    app: sbus-jobsched
---
sbus-jobsched