name: Publish NuGet
on:
  workflow_run:
    workflows: [".NET"]
    branches: [main]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Servicebus.JobScheduler.Core
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Servicebus.JobScheduler.Core/Servicebus.JobScheduler.Core.csproj
          VERSION_FILE_PATH: src/Servicebus.JobScheduler.Core/Servicebus.JobScheduler.Core.csproj
          PACKAGE_NAME: Servicebus.JobScheduler.Core
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
